### ISSUE TITLE
Principle #12 – Not Accessing Resources

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/OGC-Web-API-Guidelines#14]
• Use verbs to offer operations on resources
• /v1/transform
• Example to transform feature using different CRS
– /v1/transform/features/highway/A8?fromCRS=4326&toCRS=WGS84

**Comment by cportele** [comment]
Can you define what "(Not) Accessing Resources" are? So everything that is a noun is an "accessing resource" and everything that is a verb is a "non-accessing resource"? Then this principle is redundant and can be removed as it does not add anything.

**Comment by MichaelGordon** [comment]
I'm imagining here that what is meant is accessing operations as resources as opposed to accessing ["spatial things"](https://www.w3.org/TR/sdw-bp/#spatial-things-features-and-geometry) as resources. 

In terms of the objective of "Identify the verbs used across OGC domains.", the named spatial relationship predicates based on the DE-9IM within Simple Features would seem a potential place to start.

Indeed these could be considered ["convenience apis"](https://www.w3.org/TR/sdw-bp/#convenience-apis) on top of a more generic processing operation (referring back to the discussion in Joint OWS / Arch DWG part 2 around WPS containerised processes approach inc. Testbed 13 EO cloud work) - so that the more complex, user defined processing tasks could be supported as well as a standardised "basic" processing tasks being able to be provided through these convenience apis.

**Comment by securedimensions** [comment]
we believe that this is now addressed in master
