### ISSUE TITLE
Define Default behavior if parameters are not there.

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/OGC-Web-API-Guidelines#54]
One rule  that we are trying to use in defining APIs is that almost all parameters are optional and that there are default behavour for the lack of them

**Comment by pvretano** [comment]
I would word it slightly differently which is to say that there should be a default response at each endpoint.  For example, features at /collection/{collectionId}/items without any parameters returns N features (based on the default value of the limit parameter).  This is equivalent to saying that there should be a default value for each parameter but it is slightly different since some parameters may not have defaults defined in the specification.

Also, each response should include a minimum set of links that allow navigation to other parts of the API (e.g. links to the next/prev, link to landing page, link to source collection, alt links, etc.).

**Comment by joanma747** [comment]
New principle: Make default behaviors explicit
If you have a default behaviors ... It should be specified explicitly.
